### ISSUE TITLE
Is it exclusive to MacOS?

### ISSUE THREAD

**Issue by orijitghosh** [vianamp/MitoGraph#13]
Hi,
Is MitoGraph exclusive to Mac OS?
-Arijit

**Comment by vianamp** [comment]
At this moment MitoGraph releases are only provided for Mac OS.

However, you can compile the code yourself in other operating systems. If you want I can put in contact with people who have done that.

Best,

**Comment by orijitghosh** [comment]
Hi, sorry for the late reply. Yeah, it will be great if you can put me in touch with people who could make it work in Linux systems.

**Comment by vianamp** [comment]
Would you mind emailing me at vianamp@gmail.com? So that I can share the contacts with you?
Thanks

**Comment by ptychu** [comment]
Hi :)
I was able to compile it just now. Here's some tips.
I used fresh `ubuntu 19.10`. Packaged version of required VTK library (`libvtk7-dev`) was not good enough to compile MitoGraph. I needed to download source code from https://github.com/Kitware/VTK I checked out the `v7.1.1` release (MitoGraph requires VTK 7, so I assumed it's the closest). After installing compiled VTK I was able to compile MitoGraph. It didn't work though, because `/usr/local/lib` was not added to `/etc/ld.so.conf`. After this addition and executing `sudo ldconf` I was able to run MitoGraph. Hope it helps! Let me know if you need more detailed explenation of any of mentioned steps!
Cheers!

**Comment by vianamp** [comment]
Awesome!
Thanks

**Comment by orijitghosh** [comment]
> Hi :)
> I was able to compile it just now. Here's some tips.
> I used fresh `ubuntu 19.10`. Packaged version of required VTK library (`libvtk7-dev`) was not good enough to compile MitoGraph. I needed to download source code from https://github.com/Kitware/VTK I checked out the `v7.1.1` release (MitoGraph requires VTK 7, so I assumed it's the closest). After installing compiled VTK I was able to compile MitoGraph. It didn't work though, because `/usr/local/lib` was not added to `/etc/ld.so.conf`. After this addition and executing `sudo ldconf` I was able to run MitoGraph. Hope it helps! Let me know if you need more detailed explenation of any of mentioned steps!
> Cheers!

Thank you so much. I am sorry for the late reply.
